// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSv29MOrDC0TdRDelCPdqiLMbMC8w1iR0',
    appId: '1:216036407952:web:19f3c9a75c256f5138b615',
    messagingSenderId: '216036407952',
    projectId: 'portfolio-webapp-2611',
    authDomain: 'portfolio-webapp-2611.firebaseapp.com',
    storageBucket: 'portfolio-webapp-2611.appspot.com',
    measurementId: 'G-EHGZMT8143',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOsxOIuUZf15LrqKOVjjYYhPxKAQk9upM',
    appId: '1:216036407952:android:d1e617f0b57a0e5c38b615',
    messagingSenderId: '216036407952',
    projectId: 'portfolio-webapp-2611',
    storageBucket: 'portfolio-webapp-2611.appspot.com',
  );
}
